<?php
/**
 * Title: Leveza com Estrutura — Política de Privacidade
 * Slug: ips-twentytwentyfive-child/politica-de-privacidade
 * Categories: text
 * Description: Página completa e editável de Política de Privacidade da área privada Leveza com Estrutura.
 * Inserter: yes
 */
?>
<!-- wp:group {"tagName":"main","align":"full","className":"ips-legal-page","layout":{"type":"default"}} -->
<main class="wp-block-group alignfull ips-legal-page">

<!-- wp:group {"align":"full","className":"ips-legal-hero","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull ips-legal-hero">
  <!-- wp:columns {"align":"wide","verticalAlignment":"center","className":"ips-legal-hero__columns"} -->
  <div class="wp-block-columns alignwide are-vertically-aligned-center ips-legal-hero__columns">
    <!-- wp:column {"verticalAlignment":"center","width":"62%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:62%">
      <!-- wp:paragraph {"className":"ips-app-kicker"} --><p class="ips-app-kicker">Proteção de dados</p><!-- /wp:paragraph -->
      <!-- wp:heading {"level":1,"className":"ips-legal-hero__title"} --><h1 class="wp-block-heading ips-legal-hero__title">Política de Privacidade</h1><!-- /wp:heading -->
      <!-- wp:paragraph {"className":"ips-legal-hero__lead"} --><p class="ips-legal-hero__lead">Esta política explica como são tratados os dados pessoais na área privada de acompanhamento nutricional <strong>Leveza com Estrutura</strong>, incluindo informação relativa à saúde.</p><!-- /wp:paragraph -->
      <!-- wp:paragraph {"className":"ips-legal-update"} --><p class="ips-legal-update">Última atualização: 17 de julho de 2026</p><!-- /wp:paragraph -->
    </div><!-- /wp:column -->
    <!-- wp:column {"verticalAlignment":"center","width":"38%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:38%"><!-- wp:group {"className":"ips-legal-summary","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-summary"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Em resumo</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Os dados são utilizados para prestar e organizar o acompanhamento nutricional, proteger a conta e cumprir obrigações legais e profissionais. Não são vendidos, não são usados para publicidade e não existem decisões clínicas exclusivamente automáticas.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
  </div><!-- /wp:columns -->
</div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ips-legal-content","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull ips-legal-content">
  <!-- wp:group {"align":"wide","className":"ips-legal-article","layout":{"type":"constrained","contentSize":"900px"}} -->
  <div class="wp-block-group alignwide ips-legal-article">

    <!-- wp:group {"className":"ips-legal-notice","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-notice"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Uma política para uma área clínica privada</h3><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma trata dados de natureza pessoal e clínica. A recolha deve limitar-se ao que é relevante para o acompanhamento, com acesso restrito e utilização compatível com a finalidade comunicada.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">01</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Responsável pelo tratamento</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A responsável pela determinação das finalidades e dos meios de tratamento dos dados pessoais nesta plataforma é Inês Pinho Santos, Nutricionista com cédula profissional 5107N, NIF 229548784.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Morada profissional: Rua das Carvalhas, n.º 287, 3720-176 Ossela, Oliveira de Azeméis.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Contacto para assuntos de privacidade: <a href="mailto:geral@inespinhosantos.pt?subject=Prote%C3%A7%C3%A3o%20de%20dados">geral@inespinhosantos.pt</a>.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">02</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Âmbito desta política</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Esta política aplica-se ao tratamento realizado através da área privada <strong>Leveza com Estrutura</strong>, incluindo:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>criação e gestão da conta de cliente;</li><li>autenticação e controlo de acesso;</li><li>briefings e formulários de acompanhamento;</li><li>registos de evolução, documentos e materiais;</li><li>comunicações relacionadas com o funcionamento e com o acompanhamento;</li><li>segurança, suporte técnico e prevenção de utilização abusiva.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>O tratamento realizado noutros contextos, como consultas presenciais, faturação, newsletter ou redes sociais, pode estar sujeito a informação de privacidade adicional.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">03</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Que dados podem ser recolhidos</h2><!-- /wp:heading --><!-- wp:list --><ul><li><strong>Identificação e contacto:</strong> nome, email, telefone, data de nascimento e identificação interna de cliente.</li><li><strong>Conta e acesso:</strong> identificador de utilizadora, autenticação, recuperação de conta, permissões e estado do acesso.</li><li><strong>Acompanhamento nutricional:</strong> objetivos, rotina, hábitos alimentares, dificuldades, respostas aos briefings, evolução e próximos passos.</li><li><strong>Dados relativos à saúde:</strong> peso, medidas, patologias, sintomas, medicação, análises ou informação clínica relevante fornecida pela cliente.</li><li><strong>Fotografias e documentos:</strong> fotografias de evolução, imagens, ficheiros e documentos enviados no âmbito do acompanhamento.</li><li><strong>Comunicações:</strong> pedidos de apoio, mensagens relacionadas com a conta, respostas e contactos relevantes.</li><li><strong>Dados técnicos e de segurança:</strong> endereço IP, data e hora de acesso, navegador, dispositivo e registos necessários ao funcionamento e à segurança.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Não são recolhidos dados para publicidade comportamental nem para criação de perfis comerciais através desta área privada.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">04</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Origem dos dados</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Os dados podem ser obtidos:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>diretamente da cliente, quando cria a conta, preenche formulários ou envia informação;</li><li>pela nutricionista, quando regista informação relevante ou disponibiliza materiais;</li><li>automaticamente, em relação a dados técnicos necessários à autenticação, segurança e funcionamento;</li><li>a partir de registos anteriores do acompanhamento, quando a integração seja necessária e compatível com a finalidade original.</li></ul><!-- /wp:list --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">05</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Finalidades e bases de tratamento</h2><!-- /wp:heading --><!-- wp:list --><ul><li><strong>Prestar, organizar e personalizar o acompanhamento nutricional:</strong> execução do serviço e, para dados de saúde, prestação de cuidados por profissional sujeita a dever de confidencialidade.</li><li><strong>Gerir a conta e permitir acesso seguro:</strong> execução do serviço e interesse legítimo em assegurar funcionamento e segurança.</li><li><strong>Responder a pedidos e prestar suporte:</strong> execução do serviço e interesse legítimo em manter a continuidade.</li><li><strong>Prevenir fraude, abuso e acessos indevidos:</strong> interesse legítimo na proteção da cliente, da responsável e da infraestrutura.</li><li><strong>Cumprir obrigações legais e profissionais:</strong> cumprimento de obrigação jurídica aplicável.</li><li><strong>Declarar, exercer ou defender direitos:</strong> interesse legítimo e fundamento jurídico aplicável.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Quando um tratamento depender de consentimento, este será pedido de forma específica e separada, podendo ser retirado sem afetar a licitude do tratamento realizado antes da retirada.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">06</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dados de saúde e fotografias</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Os dados relativos à saúde são categorias especiais de dados e recebem proteção reforçada. São tratados apenas quando relevantes para o acompanhamento nutricional e no contexto da prestação de cuidados por uma profissional sujeita a deveres de confidencialidade.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>As fotografias de evolução, quando facultadas, destinam-se exclusivamente à avaliação e ao acompanhamento da própria cliente. Não serão publicadas, usadas em redes sociais, testemunhos, publicidade ou materiais promocionais sem consentimento explícito, específico e separado.</p><!-- /wp:paragraph --><!-- wp:group {"className":"ips-legal-callout","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-callout"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Sem reutilização para marketing</h3><!-- /wp:heading --><!-- wp:paragraph --><p>O facto de uma fotografia, medida ou resultado estar disponível na área privada não autoriza qualquer utilização pública ou promocional.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">07</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dados necessários e opcionais</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Alguns dados de identificação, contacto e autenticação são necessários para criar e proteger a conta. A informação clínica necessária depende do acompanhamento acordado e do contexto individual.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Campos identificados como opcionais, incluindo determinadas fotografias ou observações, podem ser deixados em branco. A ausência de informação relevante poderá limitar a personalização ou a análise.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">08</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Tecnologia, desenvolvimento e inteligência artificial</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma pode ser desenvolvida e mantida com ferramentas como GitHub, Lovable e Codex/OpenAI. Estas ferramentas destinam-se ao desenvolvimento de software e não funcionam como arquivo clínico da cliente.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Não devem ser introduzidos em prompts, repositórios de código ou ambientes de desenvolvimento dados de saúde identificáveis, fotografias clínicas ou conteúdos privados de clientes. A informação clínica de produção deve permanecer nos sistemas configurados para esse tratamento.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Não são tomadas decisões clínicas ou decisões com efeitos jurídicos baseadas exclusivamente em tratamento automatizado. Qualquer futura funcionalidade de inteligência artificial aplicada ao acompanhamento deverá ser previamente avaliada e sujeita a supervisão humana.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">09</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Prestadores de serviços e destinatários</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Os dados podem ser tratados por prestadores que atuem por conta da responsável e apenas na medida necessária às funções contratadas. As principais categorias são:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>infraestrutura de autenticação, base de dados e armazenamento, atualmente prevista através de Supabase;</li><li>alojamento e disponibilização da interface da plataforma;</li><li>serviços de segurança, manutenção e suporte técnico;</li><li>comunicações transacionais, quando sejam ativados emails de acesso, recuperação ou notificações de serviço;</li><li>consultores técnicos ou jurídicos, quando necessário e sujeitos a confidencialidade;</li><li>autoridades públicas, reguladores ou tribunais, quando exista obrigação legal ou pedido legítimo.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Os prestadores não podem utilizar os dados clínicos para fins próprios, publicidade ou comercialização. A lista atualizada dos prestadores que tratem dados pessoais pode ser solicitada através do contacto indicado nesta política.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">10</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Transferências internacionais</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Sempre que um prestador trate dados fora do Espaço Económico Europeu, a transferência deve apoiar-se num mecanismo legal adequado, como decisão de adequação, cláusulas contratuais-tipo ou outra garantia reconhecida pela legislação aplicável.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A seleção da região de armazenamento, os contratos com subcontratantes e as garantias aplicáveis devem ser confirmados antes da entrada em produção e revistos quando a infraestrutura seja alterada.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">11</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Conservação dos dados</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Os dados são conservados apenas durante o período necessário às finalidades descritas. Quando não seja possível indicar antecipadamente um prazo único, são considerados:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>a duração do acompanhamento e a necessidade de continuidade clínica;</li><li>a manutenção da conta enquanto o acesso estiver ativo ou for necessário;</li><li>obrigações legais, profissionais, fiscais ou de documentação aplicáveis;</li><li>prazos de prescrição e necessidade de defesa de direitos;</li><li>segurança, investigação de incidentes e resolução de pedidos;</li><li>pedido de apagamento, quando não exista fundamento legal para conservar os dados.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Quando deixem de ser necessários, os dados serão apagados, anonimizados ou isolados com acesso restrito, consoante o caso.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">12</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Segurança e confidencialidade</h2><!-- /wp:heading --><!-- wp:paragraph --><p>São adotadas medidas técnicas e organizativas adequadas ao risco, que devem incluir, conforme a configuração da plataforma:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>acesso autenticado e individual;</li><li>permissões limitadas por função e necessidade;</li><li>ligações cifradas e proteção das credenciais;</li><li>registos e mecanismos de deteção de acessos indevidos;</li><li>cópias de segurança e procedimentos de recuperação adequados;</li><li>atualização de software e correção de vulnerabilidades;</li><li>dever de confidencialidade de quem tenha acesso legítimo.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Apesar das medidas adotadas, nenhum sistema é absolutamente invulnerável. Uma suspeita de incidente deve ser comunicada para <a href="mailto:geral@inespinhosantos.pt">geral@inespinhosantos.pt</a>.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">13</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Cookies e mecanismos essenciais</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A área privada utiliza apenas cookies ou mecanismos equivalentes estritamente necessários para autenticação, segurança, manutenção da sessão, preferências essenciais e funcionamento técnico.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Não é utilizado Google Analytics, não existem cookies publicitários e a atividade clínica não é utilizada para publicidade comportamental.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">14</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Direitos da titular dos dados</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Nos termos aplicáveis, a titular pode solicitar:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>acesso aos dados pessoais e informação sobre o tratamento;</li><li>retificação de dados inexatos ou incompletos;</li><li>apagamento, quando não exista fundamento para conservação;</li><li>limitação do tratamento em determinadas situações;</li><li>portabilidade dos dados, quando legalmente aplicável;</li><li>oposição a tratamentos baseados em interesse legítimo;</li><li>retirada de consentimento, quando o tratamento dependa desse fundamento;</li><li>informação sobre a inexistência de decisões clínicas exclusivamente automáticas.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>O pedido pode ser enviado para <a href="mailto:geral@inespinhosantos.pt?subject=Exerc%C3%ADcio%20de%20direitos">geral@inespinhosantos.pt</a>. Poderá ser pedida informação adicional para confirmar a identidade e proteger os dados da cliente.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A titular pode ainda apresentar reclamação junto da Comissão Nacional de Proteção de Dados, sem prejuízo de procurar primeiro esclarecimento junto da responsável.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">15</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Maiores de 18 anos, alterações e contacto</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A área privada destina-se exclusivamente a pessoas com 18 ou mais anos. Não deve ser criada uma conta para uma pessoa menor de idade.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Esta política pode ser atualizada para refletir alterações legais, profissionais, técnicas ou funcionais. A data da última atualização será indicada no início da página e as alterações relevantes poderão ser comunicadas às utilizadoras.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Questões sobre privacidade ou sobre o tratamento de dados devem ser enviadas para <a href="mailto:geral@inespinhosantos.pt">geral@inespinhosantos.pt</a>.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-end","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group ips-legal-end"><!-- wp:paragraph --><p><strong>Leveza com Estrutura</strong><br>Nutricionista Inês Pinho Santos · 5107N</p><!-- /wp:paragraph --><!-- wp:buttons {"layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/termos-e-condicoes/">Termos e Condições</a></div><!-- /wp:button --><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://leveza-estruturada-app.lovable.app" target="_blank" rel="noreferrer noopener">Entrar na plataforma</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

  </div><!-- /wp:group -->
</div><!-- /wp:group -->

</main><!-- /wp:group -->
