<?php
/**
 * Title: Leveza com Estrutura — Termos e Condições
 * Slug: ips-twentytwentyfive-child/termos-e-condicoes
 * Categories: text
 * Description: Página completa e editável de Termos e Condições da área privada Leveza com Estrutura.
 * Inserter: yes
 */
?>
<!-- wp:group {"tagName":"main","align":"full","className":"ips-legal-page","layout":{"type":"default"}} -->
<main class="wp-block-group alignfull ips-legal-page">

<!-- wp:group {"align":"full","className":"ips-legal-hero","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull ips-legal-hero">
  <!-- wp:columns {"align":"wide","verticalAlignment":"center","className":"ips-legal-hero__columns"} -->
  <div class="wp-block-columns alignwide are-vertically-aligned-center ips-legal-hero__columns">
    <!-- wp:column {"verticalAlignment":"center","width":"62%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:62%">
      <!-- wp:paragraph {"className":"ips-app-kicker"} --><p class="ips-app-kicker">Informação legal</p><!-- /wp:paragraph -->
      <!-- wp:heading {"level":1,"className":"ips-legal-hero__title"} --><h1 class="wp-block-heading ips-legal-hero__title">Termos e Condições</h1><!-- /wp:heading -->
      <!-- wp:paragraph {"className":"ips-legal-hero__lead"} --><p class="ips-legal-hero__lead">Estes termos regulam o acesso e a utilização da área privada de acompanhamento nutricional <strong>Leveza com Estrutura</strong>.</p><!-- /wp:paragraph -->
      <!-- wp:paragraph {"className":"ips-legal-update"} --><p class="ips-legal-update">Última atualização: 17 de julho de 2026</p><!-- /wp:paragraph -->
    </div><!-- /wp:column -->
    <!-- wp:column {"verticalAlignment":"center","width":"38%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:38%"><!-- wp:group {"className":"ips-legal-summary","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-summary"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Em resumo</h3><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma é exclusiva para clientes maiores de 18 anos, funciona por convite e complementa o acompanhamento nutricional. O acesso é pessoal, não pode ser partilhado e não deve ser usado em situações urgentes.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
  </div><!-- /wp:columns -->
</div><!-- /wp:group -->

<!-- wp:group {"align":"full","className":"ips-legal-content","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull ips-legal-content">
  <!-- wp:group {"align":"wide","className":"ips-legal-article","layout":{"type":"constrained","contentSize":"900px"}} -->
  <div class="wp-block-group alignwide ips-legal-article">

    <!-- wp:group {"className":"ips-legal-notice","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-notice"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Leitura importante</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Ao aceder ou utilizar a plataforma, a utilizadora declara que leu e aceita estes Termos e Condições. A Política de Privacidade constitui um documento separado e complementar.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">01</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Identificação da responsável</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma <strong>Leveza com Estrutura</strong> é disponibilizada por Inês Pinho Santos, Nutricionista com cédula profissional 5107N, NIF 229548784, com morada profissional na Rua das Carvalhas, n.º 287, 3720-176 Ossela, Oliveira de Azeméis.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Contacto: <a href="mailto:geral@inespinhosantos.pt">geral@inespinhosantos.pt</a>.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">02</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Objeto e aceitação</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Estes termos regulam o acesso, a navegação e a utilização da área privada, incluindo formulários, briefings, registos, documentos, materiais e restantes funcionalidades disponibilizadas.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Quando a utilizadora não concorde com alguma disposição, não deverá utilizar a plataforma e deverá contactar a responsável para esclarecer alternativas de acompanhamento.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">03</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Natureza e finalidade da plataforma</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma é uma ferramenta complementar ao acompanhamento nutricional prestado por Inês Pinho Santos. Destina-se a:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>recolher informação relevante entre consultas;</li><li>disponibilizar briefings, orientações, documentos e materiais;</li><li>organizar registos de evolução e próximos passos;</li><li>facilitar a preparação das consultas seguintes;</li><li>melhorar a continuidade e a personalização do acompanhamento.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>O acesso está incluído no serviço de consulta enquanto fizer parte do acompanhamento acordado. Nesta fase, a plataforma não constitui uma subscrição autónoma nem é comercializada separadamente.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">04</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Acesso e elegibilidade</h2><!-- /wp:heading --><!-- wp:paragraph --><p>O acesso é reservado a clientes que:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>tenham pelo menos 18 anos;</li><li>estejam ou tenham estado em acompanhamento nutricional com Inês Pinho Santos;</li><li>tenham recebido um convite ou autorização de acesso;</li><li>utilizem a plataforma apenas para fins pessoais relacionados com o próprio acompanhamento.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Não é permitido criar ou utilizar uma conta em nome de outra pessoa, ceder o acesso ou permitir que terceiros consultem conteúdos clínicos ou pessoais associados à conta.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">05</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Conta, credenciais e segurança</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A utilizadora é responsável por manter confidenciais os seus dados de acesso e por utilizar um endereço de email ao qual apenas ela tenha acesso.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Qualquer suspeita de acesso indevido, perda de credenciais ou utilização não autorizada deve ser comunicada sem demora para <a href="mailto:geral@inespinhosantos.pt">geral@inespinhosantos.pt</a>.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A responsável poderá solicitar confirmação de identidade antes de restaurar acessos, alterar dados da conta ou fornecer informação pessoal.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">06</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Regras de utilização</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A utilizadora compromete-se a utilizar a plataforma de forma lícita, responsável e compatível com a finalidade do acompanhamento. Não é permitido:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>partilhar credenciais ou conteúdos privados com terceiros;</li><li>tentar aceder a contas, registos ou áreas sem autorização;</li><li>interferir com o funcionamento, segurança ou integridade da plataforma;</li><li>introduzir código malicioso ou automatizar acessos abusivos;</li><li>copiar, vender, publicar ou distribuir materiais protegidos;</li><li>submeter conteúdo ilegal, fraudulento ou que viole direitos de terceiros;</li><li>utilizar a plataforma para obter aconselhamento destinado a outra pessoa.</li></ul><!-- /wp:list --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">07</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Informação de saúde e acompanhamento profissional</h2><!-- /wp:heading --><!-- wp:paragraph --><p>No âmbito do acompanhamento, a utilizadora poderá fornecer dados como peso, medidas, fotografias, patologias, medicação, sintomas, hábitos alimentares, rotina e respostas aos briefings.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A informação fornecida deve ser verdadeira, atual e tão completa quanto razoavelmente necessário. Informação incorreta ou incompleta pode limitar a adequação das orientações profissionais.</p><!-- /wp:paragraph --><!-- wp:group {"className":"ips-legal-callout","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-callout"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">A plataforma não substitui a consulta.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Os registos digitais são analisados no contexto do acompanhamento profissional. A plataforma não realiza diagnóstico automático, não prescreve tratamentos de forma autónoma e não substitui avaliação médica, psicológica ou de outro profissional de saúde quando necessária.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">08</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Comunicações e situações urgentes</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma e o email geral não são canais de emergência nem garantem resposta imediata. Em caso de sintomas graves, reação adversa, agravamento súbito ou outra situação urgente, a utilizadora deve contactar o SNS 24, o 112 ou os serviços de saúde adequados.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>As mensagens enviadas através da plataforma destinam-se a apoio e organização do acompanhamento, dentro da disponibilidade profissional comunicada.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">09</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Conteúdos e propriedade intelectual</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Os textos, documentos, planos, receitas, vídeos, imagens, marcas, modelos, ferramentas e restantes materiais disponibilizados pertencem à responsável ou são utilizados com autorização.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A utilizadora recebe uma licença pessoal, limitada, não exclusiva e não transmissível para consultar e utilizar os materiais no âmbito do próprio acompanhamento. Não é permitida a reprodução, distribuição, publicação, revenda, adaptação ou exploração comercial sem autorização escrita.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">10</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Disponibilidade e serviços de terceiros</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A plataforma é atualmente disponibilizada através de serviços tecnológicos externos. Poderão ocorrer interrupções temporárias por manutenção, atualizações, falhas técnicas, segurança ou acontecimentos fora do controlo razoável da responsável.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A responsável procurará manter o serviço disponível e corrigir problemas relevantes, mas não garante funcionamento permanente, ausência total de erros ou compatibilidade com todos os dispositivos e navegadores.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">11</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Suspensão e fim do acesso</h2><!-- /wp:heading --><!-- wp:paragraph --><p>O acesso poderá ser suspenso ou terminado quando:</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>termine o acompanhamento ou deixe de existir necessidade de acesso;</li><li>seja detetada utilização abusiva, partilha de credenciais ou risco de segurança;</li><li>a utilizadora viole estes termos;</li><li>seja necessário proteger dados, sistemas ou terceiros;</li><li>a plataforma seja substituída, descontinuada ou reorganizada.</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>Quando possível e adequado, a utilizadora será informada e poderá solicitar esclarecimentos ou acesso aos dados que legalmente lhe devam ser disponibilizados.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">12</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Responsabilidade</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A responsável não responde por consequências resultantes de utilização contrária às orientações profissionais, omissão de informação relevante, partilha indevida de credenciais, falhas do equipamento ou ligação da utilizadora, ou utilização da plataforma como substituto de cuidados urgentes.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Nada nestes termos exclui responsabilidades que, por lei, não possam ser limitadas ou excluídas.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">13</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dados pessoais e mecanismos técnicos</h2><!-- /wp:heading --><!-- wp:paragraph --><p>O tratamento de dados pessoais é explicado na <a href="/politica-de-privacidade/">Política de Privacidade</a>. A plataforma utiliza apenas os mecanismos técnicos necessários à autenticação, segurança, sessão e funcionamento.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Não é utilizado Google Analytics nem são utilizados cookies publicitários nesta área.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-section","layout":{"type":"constrained"}} --><div class="wp-block-group ips-legal-section"><!-- wp:paragraph {"className":"ips-legal-number"} --><p class="ips-legal-number">14</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Alterações, lei aplicável e contacto</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Estes termos podem ser atualizados para refletir alterações legais, profissionais, técnicas ou funcionais. A data da última atualização será indicada no início da página e, quando a alteração seja relevante, poderá ser comunicada às utilizadoras.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Aplica-se a lei portuguesa. Qualquer questão deve ser enviada para <a href="mailto:geral@inespinhosantos.pt">geral@inespinhosantos.pt</a>, procurando-se uma resolução adequada antes do recurso às entidades competentes.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

    <!-- wp:group {"className":"ips-legal-end","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group ips-legal-end"><!-- wp:paragraph --><p><strong>Leveza com Estrutura</strong><br>Nutricionista Inês Pinho Santos · 5107N</p><!-- /wp:paragraph --><!-- wp:buttons {"layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/politica-de-privacidade/">Política de Privacidade</a></div><!-- /wp:button --><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://leveza-estruturada-app.lovable.app" target="_blank" rel="noreferrer noopener">Entrar na plataforma</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

  </div><!-- /wp:group -->
</div><!-- /wp:group -->

</main><!-- /wp:group -->
